---
version: '3'

volumes:
  es_data:
  redis_data:
  node_modules:

services:
  scope:
    build: .
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=secret_key
      - DJANGO_DEBUG=True
      - ES_HOSTS=elasticsearch:9200
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - node_modules:/src/node_modules
      - .:/src

  worker:
    build: .
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=secret_key
      - DJANGO_DEBUG=True
      - ES_HOSTS=elasticsearch:9200
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - node_modules:/src/node_modules
      - .:/src
    command: 'watchmedo auto-restart -p *.py -R -- celery -A scope worker -l info'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '43431:9200'

  redis:
    image: redis:4-alpine
    user: redis
    command: '--appendonly yes'
    volumes:
      - redis_data:/data
    ports:
      - '43432:6379'

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./media:/src/media:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '43430:80'
